2024-10-25 22:57:36,157 ERROR: Exception on /marketing_plan [GET] [in /Users/davidseamans/Projects/BizGrowthNexus/venv/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/davidseamans/Projects/BizGrowthNexus/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidseamans/Projects/BizGrowthNexus/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidseamans/Projects/BizGrowthNexus/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidseamans/Projects/BizGrowthNexus/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidseamans/Projects/BizGrowthNexus/venv/lib/python3.12/site-packages/flask_login/utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidseamans/Projects/BizGrowthNexus/venv/lib/python3.12/site-packages/flask_login/login_manager.py", line 187, in unauthorized
    flash(self.login_message, category=self.login_message_category)
  File "/Users/davidseamans/Projects/BizGrowthNexus/venv/lib/python3.12/site-packages/flask/helpers.py", line 323, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "/Users/davidseamans/Projects/BizGrowthNexus/venv/lib/python3.12/site-packages/flask/sessions.py", line 102, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2024-10-25 22:57:36,161 ERROR: 500 error occurred: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in /Users/davidseamans/Projects/BizGrowthNexus/app.py:188]
